services:
  php-apache:
    build: ./php
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ../public:/var/www/html
      - ../src:/var/www/src
    networks:
      - cod3r-php
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - cod3r-innout-projeto-final:/var/lib/mysql
    networks:
      - cod3r-php

volumes:
  cod3r-innout-projeto-final:

networks:
  cod3r-php:
    driver: bridge

